### ISSUE TITLE
Update Enterprise logo. Add Teams, Talent, Engagement

### ISSUE THREAD

**Issue by rennieabe** [StackExchange/Stacks-Icons#11]
Update the Enterprise logo icons with "For Enterprise" version. Add "For Teams" logo, as well as SO Talent and Engagement logos.

**Comment by aaronshekey** [comment]
@rennieabe Should "For Enterprise" replace the current version with just "Enterprise" or is this a new icon in addition to the current icon?

**Comment by rennieabe** [comment]
It replaces it. Same for "for Teams"
