### ISSUE TITLE
Add an icon for Discord

### ISSUE THREAD

**Issue by johnmwright** [StackExchange/Stacks-Icons#131]
Similar to the Slack and MSTeams icons already in Stacks, please add an icon for Discord.  Icons can be found at https://discord.com/branding

**Comment by b-kelly** [comment]
@johnmwright Is the Discord icon going to be used for an upcoming feature? If so, please reach out to the designer on the project and have them follow up on this. They know the process, so they should be able to take it from there.

**Comment by johnmwright** [comment]
Ok, I passed this on to Caro to follow whatever process they use. Thanks
