### ISSUE TITLE
New icon: download 

### ISSUE THREAD

**Issue by phoebe-leung** [StackExchange/Stacks-Icons#28]
On Stack for Business, we have a billing page that has action items to download the invoice and receipt. I think this might be an opportunity for us to add a download icon to go alongside download links (or replace if we're very tight on space).

<img width="499" alt="billing_screen" src="https://user-images.githubusercontent.com/47794687/57793382-2cb84780-770f-11e9-8e33-aead7da0a66d.png">

I found these [two icons](https://github.com/StackExchange/Stacks-Icons/files/3183627/download.zip) on Google Material design and Flaticon but thinking we might want to simplify it to a down arrow with the line underneath?

**Comment by aaronshekey** [comment]
I'm on board for this! Especially if it's in combination with a short string. `[icon] Download` with dropping the string on smallest breakpoints is a good option.

Can you work on simplifying the date column next? 😀

**Comment by aaronshekey** [comment]
https://www.figma.com/file/NxAqQAi9i5XsrZSm1WYj6tsM/Icons?node-id=0%3A1

@phoebe-leung @StackExchange/design What'cha think of this implementation?

![image](https://user-images.githubusercontent.com/1369864/57795989-ecf06080-770c-11e9-810f-c87cf6092c9c.png)

![image](https://user-images.githubusercontent.com/1369864/57796034-0396b780-770d-11e9-9606-0ee009f56fb6.png)

**Comment by aaronshekey** [comment]
Shipped in #29
