### ISSUE TITLE
New Icon: Tiny up and down arrows

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks-Icons#3]
It'd be nice to have the 16x16 up and down arrows in the image below available in Stacks and in the `Core/svg.helper`

![image](https://user-images.githubusercontent.com/1172461/47855894-23dbd600-ddbc-11e8-971e-534f4559a0b7.png)

**Comment by aaronshekey** [comment]
Thinking of closing this in lieu of using `@Svg.TrendingUp`, `@Svg.TrendingDown`, and `@Svg.TrendingNone`

@UXPiper @TedGoas ?

**Comment by TedGoas** [comment]
Yep, I'll close. I forgot about this repo.
