### ISSUE TITLE
New icon: Jira

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks-Icons#43]
Can we get an icon for Jira? They're available on [Atlassian's design system](https://atlassian.design/guidelines/marketing/resources/logo-files), though I'm not sure which one we want:

<img width="983" alt="Screen Shot 2020-01-21 at 9 09 39 AM" src="https://user-images.githubusercontent.com/1172461/72811539-dd2b0380-3c2d-11ea-9088-984b0104b1b7.png">

**Comment by aaronshekey** [comment]
Son of a... On it!
